### ISSUE TITLE
Installation und Konfiguration der InfluxDB In Docker Desktop bei dem influxDB Container auf CLI

### ISSUE THREAD

**Issue by SelHoer** [thcologne-gart/git-project#1]
In CLI funktioniert strg+v nicht! Manuelle Eingabe scheitert an Backslash.
Was kann ich tun?

**Comment by Eichi87** [comment]
Ein Rechtsklick fügt den Inhalt der Zwischenablage in das CLI ein.

**Comment by SelHoer** [comment]
Danke für die Rückmeldung. Hat mit einem Zwischenschritt über Editor funktioniert.

Ich versteh die Vorgehensweise nicht wie ein InfluxDB-user für OPCUA-Logger und Grafana anzulegen ist. 

Soll der Pfand 1:1 übernommen werden?
influx user create \
--name logger \
--password logger2020 \
--org organization

Wenn ich das personalisiere erhalte ich diese Fehlermeldung:
Error: Post "http://192.168.0.1:8086/api/v2/users": dial tcp 192.168.0.1:8086: connect: connection refused.
Error: Get "http://192.168.0.1:8086/api/v2/setup": dial tcp 192.168.0.1:8086: connect: connection refused.

**Comment by markusseyfarthhag** [comment]
@SelHoer 

Backslash signalisiert nur eine neue Zeile, die Eingabe kann auch in einer durchgehenden Zeile gemacht werden.

z.B.:

`influx config create --active --config-name <config-name> --host-url http://<ip-address>:8086 --org <org-name> --token <token>`

Das Einfügen aus der Zwischenablage funktioniert nur indirekt, da der eingefügte Text im CLI nicht mehr bearbeitet werden kann.
Man kann aber die Eingaben im Texteditor mit der IP-Adresse, ettc. befüllen und dann kopieren.

**Comment by SelHoer** [comment]
Bei Punkt 4. habe ich im Beispiel einfach mein Bucket ID eingefügt. Es folge diese Meldung.

Error: Failed to get ID for org 'organization' (do you have org-level read permission?): Get "http://192.168.0.1:8086/api/v2/orgs?org=organization": dial tcp 192.168.0.1:8086: connect: connection refused.
Error: Get "http://192.168.0.1:8086/api/v2/setup": dial tcp 192.168.0.1:8086: connect: connection refused.
See 'influx v1 dbrp create -h' for help

Grundsätzlich benötige ich Hilfe bei der Durchführung dieser Eingaben.

**Comment by Eichi87** [comment]
Das klingt nach einem Problem mit dem Port oder dem Docker Container. Grundsätzlich ist das was du gemacht hast richtig, sofern deine Organisation `organization` heißt. Auch dein Vorgehen für Schritt 4 ist richtig.
Ich würde dir empfehlen deinen Dockercontainer neu anzulegen, also die Ausführung mit `STOP` stoppen und den Container mit `DELETE` löschen. Dann den Computer einmal neustarten, damit alle Ports freigegeben werden. Nach dem Neustart den Container mit dem Kommando aus der Anleitung neu anlegen. Versuche auch mal InfluxDB als einzige Komponente ans Laufen zu bringen.

Wichtig ist, dass der verwendete Port, hier `8086` einzig von dem InfluxDB Docker Container genutzt wird. Kein Port darf gleichzeitig zwei Anwendungen zugewiesen sein.

Du kannst auch mal nachschauen ob der Port von einem anderen Programm genutzt wird. Dazu gibst du bevor InfluxDB gestartet ist `netstat -an` in die Windows Eingabeaufforderung ein und schaust dann ob es den Eintrag `TCP <ip-adresse>:8086 ...` gibt. Falls ja, musst du für InfluxDB einen anderen Port wählen.

**Comment by SelHoer** [comment]
Danke, für deine schnelle Antwort.
Ich habe alles durchgeführt. Ich bin leider nicht weiter gekommen. Gibt es Alternativen? 
8086 ist nur für InfluxDB zugewiesen. InfluxDB läuft auch im Browser.

**Comment by Eichi87** [comment]
Funktionieren denn andere InfluxDB Kommandos? Beispielsweise `Influx user list`? Dies sollte dir deine User anzeigen. Die Konfiguration (Schritt 1) konntest du erfolgreich anlegen?

Alternativ könntest du statt InfluxDB 2.0 versuchen InfluxDB 1.8 zu nutzen. `docker run --name influxDB -p 8086:8086 -v <local-folder>:/var/lib/influxdb influxdb:1.8.6`
Grundsätzlich funktioniert das auch mit dieser Version, dann müssen nur ein paar Dinge anders gemacht werden:
- Zunächst hat 1.8.6 keine Weboberfläche.
- Wenn du im CLI bist, musst du zunächst einmal `influx` eingeben.
- Um eine Datenbank anzulegen `create database <Datenbankname>`, bsp. `create database data`
- `use <Datenbankname>`, um sie als Standarddatenbank festzulegen
- Einen Admin-User Anlegen mit `create user admin with password '<Passwort>' with all privileges`
- Schritte 1 und 4 aus der Anleitung kannst du dir sparen, die restlichen Schritte funktionieren anders
- Schritte 2 und 3: `create user <Username> with password '<Passwort>'`, um Nutzer anzulegen
- Schritte 5 und 6: `grant all on <Datenbankname> to <Username>`, um Berechtigungen auf die Datenbank zu erteilen

Grundsätzlich wäre dann die Einrichtugn von InfluxDB 1.8.6 abgeschlossen und die Aufgaben sollten funktionieren.

**Comment by SelHoer** [comment]
Hallo Herr Eichberger,

hätten Sie morgen gegen 15:00 Uhr Zeit mit mir zusammen kurz über meinen Docker zu schauen? Ich konnte mit den Aufgaben noch nicht starten und wir haben nicht mehr viel Zeit zur Bearbeitung.

Sie können mich gerne unter sk000425@fh-muenster.de anschreiben.

Vielen Dank
Selin

**Comment by Eichi87** [comment]
Der Fehler wurde durch eine falsche IP Adresse für die InfluxDB config verursacht. Hier muss eure lokale IP Adresse eingetragen werden. Diese ist in der Regel nicht 192.168.0.1.
