### ISSUE TITLE
UaModeler Laden der weiteren Modelle

### ISSUE THREAD

**Issue by markusseyfarthhag** [thcologne-gart/git-project#2]
Das laden der weiteren Modelle (Machinery und Pumps) funktioniert nicht.

Als Fehler wird ein unexpected character angegeben (siehe Bild)

![Screenshot 2021-06-26 121436](https://user-images.githubusercontent.com/72081552/123509862-452e1680-d678-11eb-91fb-766654003b93.jpg)

**Comment by Eichi87** [comment]
Das liegt vermutlich an den heruntergeladenen Dateien. Bei dem Bezug von GitHub Dateien über den Browser muss die `Raw` Datei heruntergeladen werden. Rechtsklick auf `Raw` und dann `Ziel speichern unter`.

![screenshot](https://user-images.githubusercontent.com/7935497/123512069-9f81a400-d685-11eb-830e-1f7044687623.png)

Der Fehler ist auch zu erkennen, wenn du die `.xml` Datei im Editor öffnest. Die falsche Datei beginnt mit `<!DOCTYPE html>` und wird somit nicht als gültiges Dokument erkannt. Die korrekte Datei beginnt mit `<?xml version="1.0" encoding="utf-8" ?>`.

**Comment by markusseyfarthhag** [comment]
Das hat das Problem behoben.

Das mit der RAW-Datei sollte vielleicht in die Anleiteung mit aufgenommen werden.
