### ISSUE TITLE
Keine Datenanzeige im InfluxDB bei "Past ##" Time Range

### ISSUE THREAD

**Issue by KDssmnn** [thcologne-gart/git-project#3]
Derzeit hacke ich leider am Ende der dritten Aufgabe, wo die Daten von InfluxDB von opcua-Server über den opcua-logger in die InfluxDB geschrieben werden sollen. 

Ich habe alle Tätigkeiten wie im Video beschrieben durchgeführt und nach dem Befehl "npm run start" im opcua-logger-Ordner wurde alles ordnungsgemäß gestartet.

![image](https://user-images.githubusercontent.com/86559872/123546530-3bcaaa00-d75d-11eb-9568-31cbba4b9cbd.png)

Wenn ich mich nun allerdings im InfluxDB anmelde, sagt dieser mir, dass keine Ergebnisse vorliegen. Was komisch ist, dass er "temperature" findet, aber mir allerdings nicht automatisch den "value" anzeigt. s. unteres Bild.

![image](https://user-images.githubusercontent.com/86559872/123546587-851af980-d75d-11eb-9168-651ee9840360.png)

Können Sie mir dort weiterhelfen?

Hinweis: Im Programm UAExpert sieht man die Temperatur, die sich auch laufend ändert und es sind auch alle erforderlichen Container im Docker Desktop gestartet.

**Comment by Eichi87** [comment]
Scheinbar funktioniert im aktuellen build der automatisierte Abfragezeitraum nicht. Das muss ich mir genauer anschauen um dort eine dauerhafte Lösung zu finden. Für den Moment können Sie sich jedoch behelfen, indem Sie nicht "Past 1h" eingeben, sondern ein "Custom Time Range" für die letzte Stunde eingeben. Dies sollte funktionieren.

**Comment by KDssmnn** [comment]
Herzlichen Dank für den Tipp. Auf diese Weise zeigt er nun Werte an.

**Comment by Eichi87** [comment]
Der folgende Fehler kann momentan weder von mir, noch von @KDssmnn reproduziert werden:
In `Explore` bei der InfluxDB funktionieren die automatischen Time Ranges `Past ##` nicht. Eine Custom Time Range Angabe über denselben Zeitraum funktioniert jedoch.

Wenn der Fehler bei jemandem auftritt, erstelle bitte unter Angabe folgender Daten eine Antwort in diesem Issue:
* Datum und Uhrzeit
* Betriebssystem und Version
* InfluxDB Version (`influx version` im CLI eingeben)
* node-opcua Version (In der Eingabeaufforderung in dem Ordner des OPC UA Servers: `npm -v node-opcua`)
* Wird die modifizierte opcua-logger Version genutzt? (https://github.com/Eichi87/node-opcua-logger)
* Genauer Startvorgang der Komponenten nach Neustart des Systems
* Wird eine virtuelle Maschine genutzt?
* Wie sieht das Script der Abfrage bei `Explore` der InfluxDB aus? (`Script Editor` am rechten Rand klicken)
