### ISSUE TITLE
Erstellung 2. OPCUA-Server Clientport (Vorbereitungsvideo E10 und Übung 4)

### ISSUE THREAD

**Issue by trahberger** [thcologne-gart/git-project#4]
![OPCUA-Server-Fehlermeldung](https://user-images.githubusercontent.com/86884123/124358487-d1b07a00-dc20-11eb-9102-bdf2613aa10a.jpeg)

Für die Bearbeitung der Aufgabe 4 wird die Bearbeitung des Vorbereitungsvideos E10 vorausgesetzt. 
Als Grundlage hierfür muss ein zweiter OPCUA-Server parallel zum laufen gebracht werden.
Im Dockers wurde bereits ein zweiter AAS-Server (Port 4002) erstellt.
In der Eingabeaufforderung über den Befehl node <dateiname.js> (Bsp. node "server.js") wird der zweite Server gestartet.
Hierbei erfolgt jedoch eine Fehlermeldung mit der Aussage, dass die zu verwendende Endpoint-URL über den bereits verwendeten OPCUA-Server belegt ist. (siehe Screenshot)
Im Video E10 ist erkennbar, dass für beide OPCUA-Server unterschiedliche Endpoint-URLs verwendet wurden.

Es stellt sich die Frage, wie dies generiert werden kann?

**Comment by Eichi87** [comment]
Ich nehme an, dass der Port für die zweite OPC UA Serverinstanz nicht geändert wurde. Zu diesem Zweck werden in NodeOPCUA OPCUAServerOptions definiert. Zugegebenermaßen wird dies weder in der Anleitung, noch im Video erläutert.

Die in der [Linkliste](../blob/main/Vorbereitung/Linkliste.md) verlinkte Dokumentation zu NodeOPCUA kann hier Klarheit verschaffen. Die [Dokumentation](https://node-opcua.github.io/api_doc/2.32.0/index.html) listet alle möglichen OPCUAServerOptions (node-opcua-server --> OPCUAServerOptions), u.a. `port`. Dies muss hier genutzt werden, um einen bestimmten TCP Port festzulegen.

**Comment by trahberger** [comment]
Vielen Dank für den Hinweis, der Port konnte geändert werden.
