### ISSUE TITLE
opcua-logger Fehler bei Initialisierung

### ISSUE THREAD

**Issue by SelHoer** [thcologne-gart/git-project#5]
Bei der Bearbeitung der Aufgabe 3 ist folgender Fehler aufgetreten
![Fehler_opcua-logger_npm_run_start](https://user-images.githubusercontent.com/86515332/124421762-6a024800-dd62-11eb-989d-29e276935420.PNG)

Wie ist hier zu verfahren?

**Comment by Eichi87** [comment]
Das sieht nach fehlender oder fehlerhafter Berechtigung aus. Stelle bitte sicher, dass die beim logger eingetragenen zugangsdaten zur influxDB korrekt sind und dass die Berechtigung für den genutzten User ausreichen.

**Comment by SelHoer** [comment]
Ich habe die genze Installation neu aufgesetzt um falsche Login-Daten auszuschließen. Wenn ich mich bei InfluxDB einlogge kann ich sehen, dass logger und grafana members sind. Member bedeutet nicht gleich, dass auch geschrieben werden kann? Kann ich über InfluxDB im Browser die Berechtigungen anpassen?

Wie lautet der Befehl um in CLI zu löschen? Für eventuelle Anpassungen.

**Comment by Eichi87** [comment]
Es ist notwendig die v1 Authentifizierung über das CLI mit dem entsprechenden Befehl aus der [Installationsanleitung](../tree/main/Vorbereitung/Installation/InfluxDB.md) anzulegen. `influx v1 auth list` zeigt die vorhandenen Authentifizierungen an. Hier sollten grafana und influx angezeigt werden. `influx v1 auth delete` wird genutzt um Authentifizierungen zu löschen. Grundsätzlich kann `influx v1 auth -h` genutzt werden um die Hilfe anzuzeigen. `influx v1 auth delete -h` zeigt die Hilfe zu dem Löschen Befehl an. Denk auch daran die Datenbank retention policy korrekt zu setzen (`influx v1 dbrp create`).

**Comment by SelHoer** [comment]
Danke, aber passt soweit alles. Funktioniert nur nicht und ich versehe um ehrlich zu sein nicht wo der Fehler ist.  Ich habe bei der Installation alle Ein- und Ausgaben notiert. Dort konnte ich schon lesen, dass logger Lese- und Schreibrechte hat und grafana Leserechte hat.

In unserer Gruppe bin ich die einzige, die alle installiert hat. Wir kommen somit jetzt als Gruppe nicht weiter. So wie ich es gelesen habe reichen die Videos nicht aus um die Aufgaben komplett zu erledigen.

**Comment by Eichi87** [comment]
Den issue ohne Lösung zu schließen hilft aber auch nicht weiter.
Poste bitte einen Screenshot folgender abfragen:
`influx v1 dbrp list`
`influx v1 auth list`
`influx user list`
`influx bucket list`
`influx config list`
`influx org list`

Außerdem bräuchte ich die toml Datei des loggers. Den Inhalt kannst du so einfach als Code hier einfügen:
\```
_hier den Dateiinhalt posten_
\```

Lokale IP-Adresse, ports der jeweiligen Module und opc ua endpoint könnten ebenfalls noch interessant sein.

**Comment by SelHoer** [comment]
Screenshot folgender abfragen:
`influx v1 dbrp list`
`influx v1 auth list`
`influx user list`
`influx bucket list`
`influx config list`
`influx org list`
 
![Influx_abfragen_Screenshot](https://user-images.githubusercontent.com/86515332/124554357-2a0c9500-de36-11eb-97b9-2099245933cb.PNG)

Die toml Datei des loggers. Den Inhalt kannst du so einfach als Code hier einfügen:
```
[opcua]
url             = "opc.tcp://DESKTOP-3QCDQIT:26543"

[influx]
url              = "http://logger.logger2020@192.168.0.206:8086/data"

[[metrics]]
measurement        = "temperature"
datatype           = "number"
tags               = { simulation = "true" }
nodeId             = "ns=5;i=6005"
method             = "polled"
interval           = 1000
```
 
Lokale IP-Adresse: 192.168.0.206
Port: InfluxDB: 8006
Port: Grafana: 3000
opc ua endpoint: C:\opcua-logger

Danke für die gute Hilfestellung.

**Comment by Eichi87** [comment]
Bitte in der `.toml` Datei `logger.logger2020` durch `logger:logger2020` ersetzen. Username und Passwort müssen durch einen Doppelpunkt getrennt sein.
`Port: InfluxDB: 8006` soll vermutlich `Port: InfluxDB: 8086` sein?
Der OPC UA Endpoint ist vermutlich `opc.tcp://DESKTOP-3QCDQIT:26543`, nicht `C:\opcua-logger`?

Wenn der Punkt durch einen Doppelpunkt ersetzt wird, sollte das ganze funktionieren. Ich habe den kompletten Arbeitsablauf nochmal mit deinen Daten durchgespielt und konnte keinen Fehler finden - bis auf den Punkt statt des Doppelpunkts.

**Comment by SelHoer** [comment]
Danke, hat funktioniert. 

Genau der Port ist 8086 und der Endpoint ist auch opc.tcp://DESKTOP-3QCDQIT:26543.

Vielen Dank. Hoffentlich klappt jetzt alles andere ohne solche Fehler.

**Comment by Eichi87** [comment]
Dann freue ich mich, dass ich helfen konnte.
Um solche Fehler in Zukunft zu vermeiden empfehle ich, insbesondere bei URLs und Zugangsdaten auf exakte Schreibweise und Interpunktion zu achten und lieber einmal zu viel als einmal zu wenig zu überprüfen.
