### ISSUE TITLE
keinen zugriff mehr auf grafana und influx DB nach Anmeldung

### ISSUE THREAD

**Issue by ckga22** [thcologne-gart/git-project#7]
Hallo, ich habe grafana und influxDB gem. Anleitung installiert und für mich adaptiert.
Nach der Anmeldung habe ich jedoch keinen Zugriff mehr auf die Seite, d.h. nach eingabe der IP-Adresse und des Ports kommt folgende Fehlermeldung: "Hmmm...diese Seite ist leider nicht erreichbar"

Ich bitte um Hilfe zwecks Lösung des Problems.
Danke.

Viele Grüße Chris.

**Comment by gart-labor** [comment]
Läuft denn der Docker-Container für InfluxDB und Grafana? 

Bei mir sieht die Docker-Oberfläche wie auf dem Folgenden Screenshot aus. Zum starten des Containers muss der "Start"-Button getätigt werden. 
![Screenshot](https://user-images.githubusercontent.com/85674993/171837811-728cb35e-cdfe-44a8-b332-337bfdf49543.PNG)

Sobald der Container läuft ändert sich das linke Icon zu einer grünen anstatt grauen Box.

**Comment by ckga22** [comment]
ja der Docker läuft. 
![image](https://user-images.githubusercontent.com/106801520/171839831-26430665-42b9-4e9c-9801-29a0c956bd43.png)

**Comment by gart-labor** [comment]
Für mich sieht es so aus als würde nur der Container "node red" laufen (dieser hat die grüne Box neben der Bezeichnung "node red"). Die Container für influxDB und grafana sehen für mich ausgegraut aus.

**Comment by ckga22** [comment]
> Läuft denn der Docker-Container für InfluxDB und Grafana?
> 
> Bei mir sieht die Docker-Oberfläche wie auf dem Folgenden Screenshot aus. Zum starten des Containers muss der "Start"-Button getätigt werden. ![Screenshot](https://user-images.githubusercontent.com/85674993/171837811-728cb35e-cdfe-44a8-b332-337bfdf49543.PNG)
> 
> Sobald der Container läuft ändert sich das linke Icon zu einer grünen anstatt grauen Box.



> Das war das Problem. Jetzt läuft es! Danke für den Support!

**Comment by gart-labor** [comment]
Alles klar. Dann schließe ich dieses Issue.
