### ISSUE TITLE
HTTP Status 404 – Not Found bei AAS Server

### ISSUE THREAD

**Issue by chrisMuensterfh** [thcologne-gart/git-project#8]
Beim Aufstarten des Servers erhalte ich folgende Anzeige im Browser. 
Ich habe Neustarts probiert, Habe die properties Datei Quelle erneut angepasst. Ordner ausgewechselt. etc.
MyAAS.aasx Datei wurde gemäß Video angelegt
[aas.properties.txt](https://github.com/thcologne-gart/git-project/files/8839920/aas.properties.txt)
[context.properties.txt](https://github.com/thcologne-gart/git-project/files/8839921/context.properties.txt)
![CMD](https://user-images.githubusercontent.com/106913566/172049779-3c4a08c4-d2d8-4234-a9f9-927454c8af11.PNG)
![Browser](https://user-images.githubusercontent.com/106913566/172049780-4aad3745-8d5e-453b-a084-8b8601775b13.PNG)

Was könnte der Fehler sein? Danke.

**Comment by gart-labor** [comment]
In Zeile 6 deines Screenshots steht, dass dein _contextPath_ "/aasServer" ist. Versuch bitte einmal den Link in deinem Browser auf "http://localhost:4001/aasServer/shells" (alternativ: http://127.0.0.1:4001/aasServer/shells) zu ändern.
