### ISSUE TITLE
Schreiben von OPC nach AAS Server

### ISSUE THREAD

**Issue by florianrees** [thcologne-gart/git-project#9]
Bei mir "funktioniert" das schreiben von einfachen Strings in den AAS Server mit dem PUT request.
z.B.
axios.put('http://localhost:4001/aasServer/shells/AAS_Pump420---3DDA7766/aas/submodels/SystemDaten/submodel/submodelElements/Seriennummer/value', 'xxxxxxx')
		.catch(error => ( console.log(error) ));
--> Wert kommt auf AAS Server an und kann im Browser betrachtet werden -> OK

Jedoch fehlt mir der Ansatz den String aus dem OPC UA Server zu bekommen.
Ich habe diverse Versuche gestartet auf meine selbst erstellte Schreibbare Seriennummer in OPC zuzugreifen:
	const serialNumber = addressSpace.findNode('ns=5;i=6016');
Ich bekomme mit der Log Funktion folgende Ausgabe für serialNumber:
![image](https://user-images.githubusercontent.com/106755814/172434015-0a2a275f-11f9-42a0-9d51-a37fa3c80e2a.png)

Ich würde hier gerne YYYYYY auslesen.
Ich denke mir fehlt da der richtige Ansatz die Daten zu extrahieren.

Danke schoneinmal!

Viele Grüße
Florian

**Comment by Eichi87** [comment]
Da es hier weder um einen Bug noch um die Handhabung der Tools geht, würde ich mir wünschen, dass ihr das Problem gemeinsam löst. Dieser (letzte) Teil von Aufgabe 2 ist jedoch nicht für die weiteren Aufgaben erforderlich, du kannst also zunächst mit den übrigen Aufgaben fortfahren. Ein Tipp noch, die Dokumentation von NodeOPCUa enthält die entscheidende Information.

**Comment by florianrees** [comment]
Ok danke.
Ich habe die readValue() Funktion in der Doku gefunden und es funktioniert nun.

In meinem Fall oben funktioniert es mit serialNumber.readValue().value.value
